package renderer

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/marrusl/inspectah/cmd/inspectah/internal/schema"
)

// HTMLReportOptions configures the HTML report renderer.
type HTMLReportOptions struct {
	RefineMode       bool
	OriginalSnapshot *schema.InspectionSnapshot
}

// RenderHTMLReport produces the interactive HTML report.
// This is the Go port of src/inspectah/renderers/html_report.py.
// The Python version uses Jinja2 templates with PatternFly CSS.
// The Go version builds HTML programmatically and embeds PatternFly
// CSS/JS inline for a self-contained single-file report.
func RenderHTMLReport(snap *schema.InspectionSnapshot, outputDir string, opts HTMLReportOptions) error {
	ctx := buildHTMLContext(snap, outputDir, opts)

	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n")
	b.WriteString(`<html lang="en">` + "\n")
	b.WriteString("<head>\n")
	b.WriteString(`<meta charset="UTF-8"/>` + "\n")
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1"/>` + "\n")
	b.WriteString("<title>inspectah Report</title>\n")
	b.WriteString("<style>\n")
	b.WriteString(reportCSS())
	b.WriteString("</style>\n")
	b.WriteString("</head>\n")
	b.WriteString("<body>\n")

	// Header
	b.WriteString(`<header class="report-header">` + "\n")
	b.WriteString(fmt.Sprintf("<h1>inspectah Inspection Report</h1>\n"))
	b.WriteString(fmt.Sprintf("<p>%s</p>\n", html.EscapeString(ctx.osDesc)))
	if ctx.hostname != "" {
		b.WriteString(fmt.Sprintf("<p>Host: %s</p>\n", html.EscapeString(ctx.hostname)))
	}
	b.WriteString("</header>\n")

	// Summary
	b.WriteString(`<section id="summary" class="report-section">` + "\n")
	b.WriteString("<h2>Summary</h2>\n")
	b.WriteString(ctx.summaryHTML)
	b.WriteString("</section>\n")

	// Packages
	if ctx.hasPackages {
		b.WriteString(`<section id="packages" class="report-section">` + "\n")
		b.WriteString("<h2>Packages</h2>\n")
		b.WriteString(ctx.packagesHTML)
		b.WriteString("</section>\n")
	}

	// Services
	if ctx.hasServices {
		b.WriteString(`<section id="services" class="report-section">` + "\n")
		b.WriteString("<h2>Services</h2>\n")
		b.WriteString(ctx.servicesHTML)
		b.WriteString("</section>\n")
	}

	// Config
	if ctx.hasConfig {
		b.WriteString(`<section id="config" class="report-section">` + "\n")
		b.WriteString("<h2>Configuration Files</h2>\n")
		b.WriteString(ctx.configHTML)
		b.WriteString("</section>\n")
	}

	// Containerfile
	b.WriteString(`<section id="containerfile" class="report-section">` + "\n")
	b.WriteString("<h2>Containerfile</h2>\n")
	b.WriteString("<pre class=\"containerfile-pre\"><code>")
	b.WriteString(html.EscapeString(ctx.containerfileContent))
	b.WriteString("</code></pre>\n")
	b.WriteString("</section>\n")

	// Warnings
	if len(ctx.warnings) > 0 {
		b.WriteString(`<section id="warnings" class="report-section">` + "\n")
		b.WriteString("<h2>Warnings</h2>\n")
		b.WriteString("<ul>\n")
		for _, w := range ctx.warnings {
			b.WriteString(fmt.Sprintf("<li>%s</li>\n", html.EscapeString(w)))
		}
		b.WriteString("</ul>\n")
		b.WriteString("</section>\n")
	}

	// Snapshot JSON
	b.WriteString(`<section id="snapshot" class="report-section">` + "\n")
	b.WriteString("<h2>Raw Snapshot</h2>\n")
	b.WriteString(`<details><summary>Click to expand inspection-snapshot.json</summary>` + "\n")
	b.WriteString("<pre><code>")
	b.WriteString(html.EscapeString(ctx.snapshotJSON))
	b.WriteString("</code></pre>\n")
	b.WriteString("</details>\n")
	b.WriteString("</section>\n")

	// Footer
	b.WriteString(`<footer class="report-footer">` + "\n")
	b.WriteString("<p>Generated by inspectah</p>\n")
	b.WriteString("</footer>\n")

	b.WriteString("<script>\n")
	b.WriteString(reportJS())
	b.WriteString("</script>\n")
	b.WriteString("</body>\n</html>\n")

	return os.WriteFile(filepath.Join(outputDir, "report.html"), []byte(b.String()), 0644)
}

// htmlContext holds the pre-computed data for the HTML report.
type htmlContext struct {
	osDesc              string
	hostname            string
	snapshotJSON        string
	containerfileContent string
	summaryHTML         string
	packagesHTML        string
	servicesHTML        string
	configHTML          string
	warnings            []string
	hasPackages         bool
	hasServices         bool
	hasConfig           bool
}

func buildHTMLContext(snap *schema.InspectionSnapshot, outputDir string, opts HTMLReportOptions) htmlContext {
	ctx := htmlContext{}

	// OS description
	if snap.OsRelease != nil {
		if snap.OsRelease.PrettyName != "" {
			ctx.osDesc = snap.OsRelease.PrettyName
		} else {
			ctx.osDesc = snap.OsRelease.Name
		}
	} else {
		ctx.osDesc = "Unknown"
	}

	// Hostname
	if snap.Meta != nil {
		if h, ok := snap.Meta["hostname"].(string); ok {
			ctx.hostname = h
		}
	}

	// Snapshot JSON
	if data, err := json.MarshalIndent(snap, "", "  "); err == nil {
		ctx.snapshotJSON = string(data)
	}

	// Containerfile content
	cfPath := filepath.Join(outputDir, "Containerfile")
	if data, err := os.ReadFile(cfPath); err == nil {
		ctx.containerfileContent = string(data)
	} else {
		ctx.containerfileContent = "(Containerfile not generated)"
	}

	// Summary counts
	ctx.summaryHTML = buildSummaryHTML(snap)

	// Packages
	if snap.Rpm != nil && (len(snap.Rpm.PackagesAdded) > 0 || (snap.Rpm.LeafPackages != nil && len(*snap.Rpm.LeafPackages) > 0)) {
		ctx.hasPackages = true
		ctx.packagesHTML = buildPackagesHTML(snap)
	}

	// Services
	if snap.Services != nil && (len(snap.Services.EnabledUnits) > 0 || len(snap.Services.DisabledUnits) > 0) {
		ctx.hasServices = true
		ctx.servicesHTML = buildServicesHTML(snap)
	}

	// Config
	if snap.Config != nil && len(snap.Config.Files) > 0 {
		ctx.hasConfig = true
		ctx.configHTML = buildConfigHTML(snap)
	}

	// Warnings
	for _, w := range snap.Warnings {
		if msg, ok := w["message"].(string); ok {
			ctx.warnings = append(ctx.warnings, msg)
		}
	}

	return ctx
}

func buildSummaryHTML(snap *schema.InspectionSnapshot) string {
	var b strings.Builder
	b.WriteString(`<table class="summary-table">` + "\n")

	row := func(label string, value interface{}) {
		b.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%v</td></tr>\n",
			html.EscapeString(label), value))
	}

	row("System Type", snap.SystemType)

	if snap.Rpm != nil {
		addedIncluded := 0
		for _, p := range snap.Rpm.PackagesAdded {
			if p.Include {
				addedIncluded++
			}
		}
		row("Packages Added", addedIncluded)
		if snap.Rpm.LeafPackages != nil {
			row("Leaf Packages", len(*snap.Rpm.LeafPackages))
		}
		row("Version Changes", len(snap.Rpm.VersionChanges))
	}

	if snap.Config != nil {
		included := 0
		for _, f := range snap.Config.Files {
			if f.Include {
				included++
			}
		}
		row("Config Files", included)
	}

	if snap.Services != nil {
		row("Enabled Services", len(snap.Services.EnabledUnits))
		row("Disabled Services", len(snap.Services.DisabledUnits))
		row("Drop-in Overrides", len(snap.Services.DropIns))
	}

	if snap.Network != nil {
		row("NM Connections", len(snap.Network.Connections))
		row("Firewall Zones", len(snap.Network.FirewallZones))
	}

	if snap.Containers != nil {
		row("Quadlet Units", len(snap.Containers.QuadletUnits))
		row("Running Containers", len(snap.Containers.RunningContainers))
	}

	if snap.NonRpmSoftware != nil {
		row("Non-RPM Items", len(snap.NonRpmSoftware.Items))
	}

	row("Redactions", len(snap.Redactions))
	row("Warnings", len(snap.Warnings))

	b.WriteString("</table>\n")
	return b.String()
}

func buildPackagesHTML(snap *schema.InspectionSnapshot) string {
	var b strings.Builder

	if snap.Rpm.LeafPackages != nil && len(*snap.Rpm.LeafPackages) > 0 {
		b.WriteString(fmt.Sprintf("<p>%d leaf package(s):</p>\n", len(*snap.Rpm.LeafPackages)))
		b.WriteString("<ul>\n")
		pkgs := make([]string, len(*snap.Rpm.LeafPackages))
		copy(pkgs, *snap.Rpm.LeafPackages)
		sort.Strings(pkgs)
		for _, name := range pkgs {
			b.WriteString(fmt.Sprintf("<li>%s</li>\n", html.EscapeString(name)))
		}
		b.WriteString("</ul>\n")
	}

	included := 0
	for _, p := range snap.Rpm.PackagesAdded {
		if p.Include {
			included++
		}
	}
	if included > 0 {
		b.WriteString(fmt.Sprintf("<p>%d added package(s):</p>\n", included))
		b.WriteString(`<table class="data-table">` + "\n")
		b.WriteString("<tr><th>Name</th><th>Version</th><th>Arch</th><th>Source Repo</th></tr>\n")
		for _, p := range snap.Rpm.PackagesAdded {
			if !p.Include {
				continue
			}
			b.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s-%s</td><td>%s</td><td>%s</td></tr>\n",
				html.EscapeString(p.Name),
				html.EscapeString(p.Version),
				html.EscapeString(p.Release),
				html.EscapeString(p.Arch),
				html.EscapeString(p.SourceRepo)))
		}
		b.WriteString("</table>\n")
	}

	return b.String()
}

func buildServicesHTML(snap *schema.InspectionSnapshot) string {
	var b strings.Builder

	if len(snap.Services.EnabledUnits) > 0 {
		b.WriteString(fmt.Sprintf("<p>%d enabled unit(s):</p>\n", len(snap.Services.EnabledUnits)))
		b.WriteString("<ul>\n")
		for _, u := range snap.Services.EnabledUnits {
			b.WriteString(fmt.Sprintf("<li>%s</li>\n", html.EscapeString(u)))
		}
		b.WriteString("</ul>\n")
	}

	if len(snap.Services.DisabledUnits) > 0 {
		b.WriteString(fmt.Sprintf("<p>%d disabled unit(s):</p>\n", len(snap.Services.DisabledUnits)))
		b.WriteString("<ul>\n")
		for _, u := range snap.Services.DisabledUnits {
			b.WriteString(fmt.Sprintf("<li>%s</li>\n", html.EscapeString(u)))
		}
		b.WriteString("</ul>\n")
	}

	return b.String()
}

func buildConfigHTML(snap *schema.InspectionSnapshot) string {
	var b strings.Builder

	included := 0
	for _, f := range snap.Config.Files {
		if f.Include {
			included++
		}
	}
	b.WriteString(fmt.Sprintf("<p>%d config file(s) captured:</p>\n", included))
	b.WriteString(`<table class="data-table">` + "\n")
	b.WriteString("<tr><th>Path</th><th>Kind</th><th>Category</th></tr>\n")
	for _, f := range snap.Config.Files {
		if !f.Include {
			continue
		}
		b.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s</td><td>%s</td></tr>\n",
			html.EscapeString(f.Path),
			html.EscapeString(string(f.Kind)),
			html.EscapeString(string(f.Category))))
	}
	b.WriteString("</table>\n")

	return b.String()
}

// reportCSS returns the embedded CSS for the HTML report.
func reportCSS() string {
	return `
:root {
  --bg: #1b1d21;
  --surface: #25282d;
  --text: #e0e0e0;
  --text-muted: #a0a0a0;
  --border: #3c3f44;
  --accent: #4394e5;
  --accent-bg: #1a3a5c;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  margin: 0;
  padding: 0;
  line-height: 1.5;
}
.report-header {
  background: var(--surface);
  padding: 1.5rem 2rem;
  border-bottom: 1px solid var(--border);
}
.report-header h1 { margin: 0 0 0.25rem 0; font-size: 1.5rem; }
.report-header p { margin: 0; color: var(--text-muted); }
.report-section {
  max-width: 1200px;
  margin: 1.5rem auto;
  padding: 0 2rem;
}
.report-section h2 {
  font-size: 1.2rem;
  border-bottom: 1px solid var(--border);
  padding-bottom: 0.5rem;
  margin-bottom: 1rem;
}
.summary-table, .data-table {
  border-collapse: collapse;
  width: 100%;
  margin-bottom: 1rem;
}
.summary-table td, .data-table td, .data-table th {
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
}
.summary-table td:first-child { font-weight: 600; width: 200px; }
.data-table th {
  background: var(--surface);
  text-align: left;
  font-weight: 600;
}
pre {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 1rem;
  overflow-x: auto;
  font-size: 0.85rem;
}
code { font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace; }
details summary { cursor: pointer; color: var(--accent); }
.report-footer {
  text-align: center;
  padding: 2rem;
  color: var(--text-muted);
  font-size: 0.85rem;
}
ul { padding-left: 1.5rem; }
`
}

// reportJS returns minimal JavaScript for the HTML report.
func reportJS() string {
	return `
document.querySelectorAll('details summary').forEach(s => {
  s.addEventListener('click', () => {
    const d = s.parentElement;
    d.open = !d.open;
  });
});
`
}
