[app]
name = driftify-demo
environment = production
log_level = info

# BEGIN DRIFTIFY fake-secrets-app
aws_access_key_id = REDACTED_AWS_KEY_1a5d44a2
aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# END DRIFTIFY fake-secrets-app

# BEGIN DRIFTIFY fake-secrets-standard
github_pat = ghp_xxxxxxxxxxDRIFTIFYFAKExxxxxxxxxx
# END DRIFTIFY fake-secrets-standard
